console.log("typeof(100)      :", typeof 100);
console.log("typeof(73.9)     :", typeof 73.9);
console.log("typeof(NaN)      :", typeof NaN);
console.log('typeof("Water")  :', typeof "Water");
console.log("typeof(false)    :", typeof false);
console.log("typeof(9 != 11)  :", typeof (9 != 11));
console.log('"Orang" + "e"    :', "Orang" + "e");
console.log('"Orange" - "s"   :', "Orange" - "s");
console.log('"4" + "8"        :', "4" + "8");
console.log('"4" - "8"        :', "4" - "8");
console.log('"name" + 3       :', "name" + 3);
console.log('"name" - 3       :', "name" - 3);
console.log('82 * "word"      :', 82 * "word");
console.log('1 + "hello"      :', 1 + "hello");
console.log('"hello" + 1      :', "hello" + 1);
console.log("1 + true         :", 1 + true);
console.log('"hello" + true   :', "hello" + true);
console.log("typeof(Infinity) :", typeof Infinity);
console.log("1 == '1'         :", 1 == "1");
console.log("1 === '1'        :", 1 === "1");
